name: Automatic Changelog

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Generate changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        output: CHANGELOG.md
        pullRequests: true
        prWoLabels: true
        issues: true
        issuesWoLabels: true
        author: true
        unreleased: true
        compareLink: true
        filterByMilestone: false
        stripHeaders: false
        stripGeneratorNotice: false
        
    - name: Commit and push changelog
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if git diff --quiet CHANGELOG.md; then
          echo "No changes to changelog"
          exit 0
        fi
        
        git add CHANGELOG.md
        git commit -m "docs: update changelog [skip ci]" || exit 0
        git push